name: din
description: >
  Dart API for Discord.
version: 0.1.0-alpha
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/din

environment:
  sdk: ">=1.25.0-dev <2.0.0-dev.infinity"

dependencies:
  async: ">=1.4.0 <2.0.0"
  meta: ">=0.11.0 <2.0.0"

dev_dependencies:
  # Scripting in tool/**
  args: ">= 0.13.0 <2.0.0"
  io: ">=0.1.0 <0.3.0"
  shelf_static: "^0.2.0"

  # Generators (both in tool/** _and_ lib/src/generators/**)
  build: "^0.10.0"
  build_runner: ">=0.4.0 <0.6.0"
  code_builder: "^2.0.0-alpha+1"
  source_gen: "^0.7.0"

  # Tests.
  build_test: "^0.7.0"
  test: "^0.12.0"
